### ISSUE TITLE
Does not start Scrobbling

### ISSUE THREAD

**Issue by mlindner** [Atelier-Shiori/malupdaterosx-cocoa#21]
Even after I log in the application will refuse to start scrobbling. If I quit it and re-open it it erases any past settings and forces me to type in my username and password again as if it is the first time I used the program. I am on Mac OS X 10.8.5.

**Comment by chikorita157** [comment]
I have confirmed that there is a bug in Mountain Lion with the program not saving the password to the keychain. To make it work, launch Keychain Access. Click File > New Password Item.

Create the following Keychain Item

Keychain Item Name: MAL Updater OS X

Acccount Name: (Your MyAnimeList Username)

Password:  (Your MyAnimeList password)

Relaunch and open Preferences. Click the login settings and there should be an account saved. This does not apply to 10.9 or later as it saves the keychain login properly. There might not be a fix since 10.8 is unsupported and not that many people are using that operating system.

**Comment by mlindner** [comment]
Awesome! That seems to have done it. You should probably throw this in the documentation which would help a lot of people probably.

**Comment by mlindner** [comment]
Also you say that 10.8 is unsupported but your website says otherwise: http://malupdaterosx.ateliershiori.moe/

> MAL Updater OS X requires OS X Mountain Lion or later and a MyAnimeList account. Compatable with OS X El Capitan and macOS Sierra Developer Beta.

**Comment by chikorita157** [comment]
It seems that the latest version of SMKeychain does not work at all with OS X Mountain Lion as it won't store any password, only can retrieve it. Using an earlier version which is almost three years old fixes the issues and doesn't seem to have any issues with the latest OS.  I will consider this issue fixed.

https://github.com/Atelier-Shiori/malupdaterosx-cocoa/commit/9369f9b8cbc60bb36ab7ac641a8e72868f66084d
