### ISSUE TITLE
Fails to find title, then fails to correct title

### ISSUE THREAD

**Issue by mlindner** [Atelier-Shiori/malupdaterosx-cocoa#23]
When using the program to detect on the attached URL, it initially fails to find the title and when attempts to correct it are made it then additionally fails to correct it. The corrected title appears in the exceptions list but it continues to be unable to detect it.

 http://www.crunchyroll.com/mob-psycho-100/episode-1-self-proclaimed-psychic-reigen-arataka-and-mob-715985

**Comment by chikorita157** [comment]
{"result":[{"browser":"Safari","title":"Mob Psycho 100","season":1,"site":"crunchyroll","episode":100}]}

Yep, that is an issue with the stream detection and the regex needs to be revised to fix this since it believes 100 is an episode number. Will be fixed in next release

**Comment by chikorita157** [comment]
Fixed with https://github.com/Atelier-Shiori/detectstream/commit/c49467dd54dba739a554c53c7606f7da3fb00687

{"result":[{"browser":"Safari","title":"Mob Psycho 100","season":1,"site":"crunchyroll","episode":1}]}

The title now parses properly along with the episode number.

You can replace the detectstream by downloading it from here: https://github.com/Atelier-Shiori/detectstream/releases/tag/aug-20-2016 . I will release a new build with the updated version once I squash some more bugs.
