### ISSUE TITLE
Title correction no longer works in latest update

### ISSUE THREAD

**Issue by mlindner** [Atelier-Shiori/malupdaterosx-cocoa#35]
If I try and play a file with the filename "[HorribleSubs] Re-Creators - 01v2 [1080p].mkv" it immediately pops up a pop up window (please don't do this, this is really annoying new feature) and asks me to select a correction. If I select the top correction, it pops up a window in the upper left corner that says correction failed. Every 5 minutes it will continue to pop up a window. The program is unusable right now.

**Comment by chikorita157** [comment]
Note that you can turn this feature off in the preferences. I will change it to not be turned on by default.

**Comment by chikorita157** [comment]
It's the "Show correction if title is not found" option. As for correction not working, I will look into that.

**Comment by chikorita157** [comment]
From investigation, correction does work, but not with Re-Creators. I added an auto exception rule and it seems that it's not detecting it. It's probably something with the isequaltostring or something. I will look into it later today.

**Comment by chikorita157** [comment]
It seems to be an issue with colons being removed when an exception rule is applied. Since a colon is not a valid character, it's removed when looking for a match. This can affect the search results with the title not being returned in the results, causing it to not be found. I made a change that it will remove the colons when finding the title match from the search results. 

I will release a minor fix build soon to resolve this issue. Also, it's not necessary to add a rule manually since it's added to the auto exception rules. Just update the auto exceptions data in preferences.
