### ISSUE TITLE
Make MAL Updater OSX find the correct title

### ISSUE THREAD

**Issue by mlindner** [Atelier-Shiori/malupdaterosx-cocoa#38]
MAL Updater OSX seems to fail to find the title for every anime every time. Even if the title matches exactly it will fail to actually find it. I have exceptions added for example that map "Frame Arms Girl" to the title "Frame Arms Girl" because it couldn't find the title "Frame Arms Girl". This is really weird. Even when it does find a title, it will pick the wrong title every time when it first sees a show. It seems to use some wrong regex to find the title match, but when you go to do the correction the title shows up as the first item in the list.

The program should use the first item in that list as the default selection, rather than whatever method it is using currently.

**Comment by chikorita157** [comment]
I have tested Frame Arms Girl and it detects properly. Can you give me the filename of the file you are trying to update?

**Comment by mlindner** [comment]
I have redownloaded MAL Updater.

I just attempted it again and I can't get it to reproduce, but this is a long standing minor issue that I've always encountered. It usually happens the first time I try to watch a new series.

When I see this again I will file another report.

**Comment by chikorita157** [comment]
Also MAL Search apis in Atarashij-API is not perfect since it doesn't report all the alternative titles in the search results. There is a newer version I will eventually implement. For more accurate searches, try enabling Kitsu Search API as it can bring back MAL IDs and is a bit more accurate due to having alternative titles information.
