### ISSUE TITLE
Start/Finish Date

### ISSUE THREAD

**Issue by TopoR** [Atelier-Shiori/malupdaterosx-cocoa#41]
Thanks for the awesome app! 
It'll be nice to see, that app sets start/finish date (and also ask about score when mark anime as "Completed" while without score).

**Comment by chikorita157** [comment]
Will be implemented in a future release

**Comment by chikorita157** [comment]
Implemented with https://github.com/Atelier-Shiori/malupdaterosx-cocoa/commit/c8c17a8aa916a068b1c2348ac3bf98c37eaa92e9

![2017-10-10_16-02-50](https://user-images.githubusercontent.com/161183/31407935-c054dd60-add4-11e7-8c40-d2a0cfb72202.png)

It required me to call the update API for titles that needed to be added since for some reason, the start date would not apply to the list.
