### ISSUE TITLE
VLC Detecting

### ISSUE THREAD

**Issue by TopoR** [Atelier-Shiori/malupdaterosx-cocoa#42]
Hmm, it seems that on my macbook with macOS 10.12.6 VLC is no more detected by MALU OSX (both, stable and beta). Tried versions 2.2.6 and 3.0. Still always in "idle" state.
Since I've moved to the mpv-based IINA it's not a big deal, but still.

**Comment by chikorita157** [comment]
This is fixed already, but I haven't updated detectionkit that contains the fix. Apparently, lsof doesn't work with VLC anymore, but require the use of applescript. Since the player list is in a JSON file, you just need to replace this file with this

https://github.com/Atelier-Shiori/DetectionKit/blob/master/DetectionKit/supportedplayers.json

Navigate to this directory: /Applications/MAL Updater OS X.app/Contents/Frameworks/DetectionKit.framework/Versions/A/Resources (assuming MAL Updater OS X is in the Applications folder) and replace the supportedplayers.json file with the one above. This path can be open by clicking Go > Go to Folder and copying the path above. The framework will be updated in 2.3.7, releasing in a few weeks.
