### ISSUE TITLE
Lacking a bit of some QoL things

### ISSUE THREAD

**Issue by tsundereikemen** [Atelier-Shiori/malupdaterosx-cocoa#44]
I like it so far however the lack of editing other details when adding a title is missing. Like being able to add when you started watching/reading a title and completing it etc. which MAL has if you go on the title page and clicking of Edit Details - which you shouldn't be forced to do, imo, since you download this app just to be able to edit things after all.

One other thing is the lack of other details about the titles on the app itself. Like for animes: the Studio that produced them or the date they were released; the absence of options for Categories at the top of the lists (Title, Progress, Score, etc) in the Preferences is also sort of lacking. And with the small window, it scrolls to the right and it can get annoying instead of being able to scroll up and down on the list alone.

Otherwise, everything is okay but it does need more polishing and hopefully it can be added in? Good work on it so far.

**Comment by chikorita157** [comment]
The missing features you are talking about are features that are in MAL Library. MAL Updater OS X is only used to automatically update your list based on what you are watching in a video player. MAL Library focuses on list management and title discovery, which allows one to view information about titles and manage list entries. They are separate programs since MAL Updater OS X cannot be on the Mac App Store since it won't work in a sandbox.

**Comment by tsundereikemen** [comment]
Oh whoops my bad, yes I meant on the MAL Library actually. I apologise if I
had sent it on the wrong application. However, all of those I mentioned are
what was missing on it.

Unless you're telling me that those things are actually on the app store
but it requires that I have to pay for it to get those extra
settings/options?

**Comment by chikorita157** [comment]
The free version is available on the main website, but it will only support Anime list management, anime list importing, history, messaging, title discovery for anime only. I plan to add the additional fields in the future as long it's provided by the API.

As for paying for the extra features, yes, you would have to either buy a donation license or download it from the App Store. While the program is open source, it cost money to maintain the Apple Developers Program and the hosting to host the unofficial MAL API since the official one is lacking. It's allowable for Open Source software to be paid as other projects do it to support their development. However, anyone is free to compile their own versions. Note that if you do compile your own version, you must use your own Unofficial MAL API server as using the default one is against the terms of service with the unofficial MAL API set as default.
