### ISSUE TITLE
MAL Updater OSX Unusable because of absurd weekly use limit

### ISSUE THREAD

**Issue by mlindner** [Atelier-Shiori/malupdaterosx-cocoa#45]
Please remove the recently added weekly use limit. This attempt to scam people out of their money for an open source product is beyond absurd. I reported bugs to you many times to help assist you and this is what I get for it?

**Comment by chikorita157** [comment]
The problem is I do not have the money to keep supporting the application since it cost money to maintain the Apple's Developer Program (which cost $99). The problem is, not that many people donate and developing these applications are currently my full time job until I can find full time work. I am facing hard times and I cannot give out the application for free, especially since I spent a lot of time on it. If I can't generate the funds to cover most of the server, I would have to cease all development. 

I know the limit is making people angry, but if there is more people donating or supporting my Patreon, I wouldn't have to do this. The last few months, there were hardly any donations, which I have to make a hard choice. Would rasing it to something like 30-50 will solve this issue?

**Comment by chikorita157** [comment]
See https://github.com/Atelier-Shiori/malupdaterosx-cocoa/releases/tag/2.3.11

**Comment by mlindner** [comment]
Hey, thanks for the changes and sorry for the anger in my post. For your effort I donated a little extra through paypal to help cover you some. Hope it helps.
